coverage:
  range: 100..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: error

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - type: project
        target: 100%
        threshold: 0%
      - type: patch
        target: 100%
        threshold: 0%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: foundry
      paths:
        - contracts
        - reference
      carryforward: true
      statuses:
        - type: project
          target: 100%
          threshold: 0%
        - type: patch
          target: 100%
          threshold: 0%

ignore:
  - offerers
  - script
  - test
