// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

enum ErrorType {
    CORE_CONSIDERATION_ERROR,
    TOKEN_TRANSFER_ERROR,
    SIGNATURE_VERIFICATION_ERROR,
    REENTRANCY_ERROR,
    CONDUIT_ERROR,
    ZONE_ERROR,
    AMOUNT_DERIVATION_ERROR,
    TRANSFER_HELPER_ERROR,
    CRITERIA_RESOLUTION_ERROR,
    FULFILLMENT_APPLICATION_ERROR,
    PAUSABLE_ZONE_ERROR,
    ZONE_INTERACTION_ERROR
}

enum CoreConsiderationErrors {
    BAD_FRACTION,
    CANNOT_CANCEL_ORDER,
    CONSIDERATION_LENGTH_NOT_EQUAL_TO_TOTAL_ORIGINAL,
    CONSIDERATION_NOT_MET,
    INSUFFICIENT_NATIVE_TOKENS_SUPPLIED,
    INVALID_BASIC_ORDER_PARAMETER_ENCODING,
    INVALID_CALL_TO_CONDUIT,
    INVALID_MSG_VALUE,
    INVALID_NATIVE_OFFER_ITEM,
    INVALID_TIME,
    MISMATCHED_OFFER_AND_CONSIDERATION_COMPONENTS,
    MISSING_ORIGINAL_CONSIDERATION_ITEMS,
    NO_SPECIFIED_ORDERS_AVAILABLE,
    ORDER_ALREADY_FILLED,
    ORDER_IS_CANCELLED,
    ORDER_PARTIALLY_FILLED,
    PARTIAL_FILLS_NOT_ENABLED_FOR_ORDER
}

enum TokenTransferrerErrors {
    INVALID_ERC721_TRANSFER_AMOUNT,
    MISSING_ITEM_AMOUNT,
    UNUSED_ITEM_PARAMETERS,
    TOKEN_TRANSFER_GENERIC_FAILURE,
    ERC1155_BATCH_TRANSFER_GENERIC_FAILURE,
    BAD_RETURN_VALUE_FROM_ERC20_ON_TRANSFER,
    NO_CONTRACT,
    INVALID1155_BATCH_TRANSFER_ENCODING
}

enum SignatureVerificationErrors {
    BAD_SIGNATURE_V,
    INVALID_SIGNER,
    INVALID_SIGNATURE,
    BAD_CONTRACT_SIGNATURE
}

enum ReentrancyErrors {
    NO_REENTRANT_CALLS
}

enum AmountDerivationErrors {
    INEXACT_FRACTION
}

enum TransferHelperErrors {
    INVALID_ITEM_TYPE,
    INVALID_ERC721_TRANSFER_AMOUNT,
    INVALID_ERC721_RECIPIENT,
    ERC721_RECEIVER_ERROR_REVERT_BYTES,
    ERC721_RECEIVER_ERROR_REVERT_STRING,
    INVALID_ERC20_IDENTIFIER,
    RECIPIENT_CANNOT_BE_ZERO_ADDRESS,
    INVALID_CONDUIT,
    CONDUIT_ERROR_REVERT_STRING,
    CONDUIT_ERROR_REVERT_BYTES
}

enum CriteriaResolutionErrors {
    ORDER_CRITERIA_RESOLVER_OUT_OF_RANGE,
    UNRESOLVED_OFFER_CRITERIA,
    UNRESOLVED_CONSIDERATION_CRITERIA,
    OFFER_CRITERIA_RESOLVER_OUT_OF_RANGE,
    CONSIDERATION_CRITERIA_RESOLVER_OUT_OF_RANGE,
    CRITERIA_NOT_ENABLED_FOR_ITEM,
    INVALID_PROOF
}

enum FulfillmentApplicationErrors {
    MISSING_FULFILLMENT_COMPONENT_ON_AGGREGATION,
    OFFER_AND_CONSIDERATION_REQUIRED_ON_FULFILLMENT,
    MISMATCHED_FULFILLMENT_OFFER_AND_CONSIDERATION_COMPONENTS,
    INVALID_FULFILLMENT_COMPONENT_DATA
}

enum PausableZoneErrors {
    INVALID_PAUSER,
    INVALID_OPERATOR,
    INVALID_CONTROLLER,
    ZONE_ALREADY_EXISTS,
    CALLER_IS_NOT_OWNER,
    CALLER_IS_NOT_OPERATOR,
    OWNER_CAN_NOT_BE_SET_AS_ZERO,
    PAUSER_CAN_NOT_BE_SET_AS_ZERO,
    CALLER_IS_NOT_POTENTIAL_OWNER
}

enum ZoneInteractionErrors {
    INVALID_RESTRICTED_ORDER,
    INVALID_CONTRACT_ORDER
}
