/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type AssetStruct = {
  assetType: BigNumberish;
  token: string;
  identifier: BigNumberish;
  amount: BigNumberish;
};

export type AssetStructOutput = [number, string, BigNumber, BigNumber] & {
  assetType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
};

export type ReceivedAssetStruct = {
  assetType: BigNumberish;
  token: string;
  identifier: BigNumberish;
  amount: BigNumberish;
  account: string;
};

export type ReceivedAssetStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  assetType: number;
  token: string;
  identifier: BigNumber;
  amount: BigNumber;
  account: string;
};

export type OrderParametersStruct = {
  offer: AssetStruct[];
  consideration: ReceivedAssetStruct[];
  startTime: BigNumberish;
  endTime: BigNumberish;
  offerer: string;
  salt: BigNumberish;
  facilitator: string;
  nonce: BigNumberish;
};

export type OrderParametersStructOutput = [
  AssetStructOutput[],
  ReceivedAssetStructOutput[],
  BigNumber,
  BigNumber,
  string,
  BigNumber,
  string,
  BigNumber
] & {
  offer: AssetStructOutput[];
  consideration: ReceivedAssetStructOutput[];
  startTime: BigNumber;
  endTime: BigNumber;
  offerer: string;
  salt: BigNumber;
  facilitator: string;
  nonce: BigNumber;
};

export type OrderStruct = {
  parameters: OrderParametersStruct;
  signature: BytesLike;
};

export type OrderStructOutput = [OrderParametersStructOutput, string] & {
  parameters: OrderParametersStructOutput;
  signature: string;
};

export type AdvancedAssetStruct = {
  assetType: BigNumberish;
  token: string;
  identifierOrCriteria: BigNumberish;
  startAmount: BigNumberish;
  endAmount: BigNumberish;
};

export type AdvancedAssetStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  assetType: number;
  token: string;
  identifierOrCriteria: BigNumber;
  startAmount: BigNumber;
  endAmount: BigNumber;
};

export type AdvancedReceivedAssetStruct = {
  assetType: BigNumberish;
  token: string;
  identifierOrCriteria: BigNumberish;
  startAmount: BigNumberish;
  endAmount: BigNumberish;
  account: string;
};

export type AdvancedReceivedAssetStructOutput = [
  number,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  string
] & {
  assetType: number;
  token: string;
  identifierOrCriteria: BigNumber;
  startAmount: BigNumber;
  endAmount: BigNumber;
  account: string;
};

export type AdvancedOrderParametersStruct = {
  offer: AdvancedAssetStruct[];
  consideration: AdvancedReceivedAssetStruct[];
  startTime: BigNumberish;
  endTime: BigNumberish;
  offerer: string;
  salt: BigNumberish;
  facilitator: string;
  nonce: BigNumberish;
};

export type AdvancedOrderParametersStructOutput = [
  AdvancedAssetStructOutput[],
  AdvancedReceivedAssetStructOutput[],
  BigNumber,
  BigNumber,
  string,
  BigNumber,
  string,
  BigNumber
] & {
  offer: AdvancedAssetStructOutput[];
  consideration: AdvancedReceivedAssetStructOutput[];
  startTime: BigNumber;
  endTime: BigNumber;
  offerer: string;
  salt: BigNumber;
  facilitator: string;
  nonce: BigNumber;
};

export type AdvancedOrderStruct = {
  parameters: AdvancedOrderParametersStruct;
  signature: BytesLike;
};

export type AdvancedOrderStructOutput = [
  AdvancedOrderParametersStructOutput,
  string
] & { parameters: AdvancedOrderParametersStructOutput; signature: string };

export type AdvancedFulfillmentComponentStruct = {
  orderIndex: BigNumberish;
  assetIndex: BigNumberish;
  maximumFulfillmentAmount: BigNumberish;
  criteriaProof: BytesLike[];
};

export type AdvancedFulfillmentComponentStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  string[]
] & {
  orderIndex: BigNumber;
  assetIndex: BigNumber;
  maximumFulfillmentAmount: BigNumber;
  criteriaProof: string[];
};

export type AdvancedFulfillmentStruct = {
  identifier: BigNumberish;
  offerComponents: AdvancedFulfillmentComponentStruct[];
  considerationComponents: AdvancedFulfillmentComponentStruct[];
};

export type AdvancedFulfillmentStructOutput = [
  BigNumber,
  AdvancedFulfillmentComponentStructOutput[],
  AdvancedFulfillmentComponentStructOutput[]
] & {
  identifier: BigNumber;
  offerComponents: AdvancedFulfillmentComponentStructOutput[];
  considerationComponents: AdvancedFulfillmentComponentStructOutput[];
};

export type FulfillmentComponentStruct = {
  orderIndex: BigNumberish;
  assetIndex: BigNumberish;
};

export type FulfillmentComponentStructOutput = [BigNumber, BigNumber] & {
  orderIndex: BigNumber;
  assetIndex: BigNumber;
};

export type FulfillmentStruct = {
  offerComponents: FulfillmentComponentStruct[];
  considerationComponents: FulfillmentComponentStruct[];
};

export type FulfillmentStructOutput = [
  FulfillmentComponentStructOutput[],
  FulfillmentComponentStructOutput[]
] & {
  offerComponents: FulfillmentComponentStructOutput[];
  considerationComponents: FulfillmentComponentStructOutput[];
};

export type ExecutionStruct = { asset: ReceivedAssetStruct; offerer: string };

export type ExecutionStructOutput = [ReceivedAssetStructOutput, string] & {
  asset: ReceivedAssetStructOutput;
  offerer: string;
};

export interface ConsiderationInterface extends utils.Interface {
  contractName: "Consideration";
  functions: {
    "DOMAIN_SEPARATOR()": FunctionFragment;
    "cancel((((uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[],uint256,uint256,address,uint256,address,uint256),bytes)[])": FunctionFragment;
    "facilitatorNonces(address,address)": FunctionFragment;
    "fulfillOrder((((uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[],uint256,uint256,address,uint256,address,uint256),bytes))": FunctionFragment;
    "hash(((uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[],uint256,uint256,address,uint256,address,uint256))": FunctionFragment;
    "matchAdvancedOrders((((uint8,address,uint256,uint256,uint256)[],(uint8,address,uint256,uint256,uint256,address)[],uint256,uint256,address,uint256,address,uint256),bytes)[],(uint256,(uint256,uint256,uint256,bytes32[])[],(uint256,uint256,uint256,bytes32[])[])[])": FunctionFragment;
    "matchOrders((((uint8,address,uint256,uint256)[],(uint8,address,uint256,uint256,address)[],uint256,uint256,address,uint256,address,uint256),bytes)[],((uint256,uint256)[],(uint256,uint256)[])[])": FunctionFragment;
    "name()": FunctionFragment;
    "orderUsed(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [OrderStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "facilitatorNonces",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillOrder",
    values: [OrderStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "hash",
    values: [OrderParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "matchAdvancedOrders",
    values: [AdvancedOrderStruct[], AdvancedFulfillmentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "matchOrders",
    values: [OrderStruct[], FulfillmentStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "orderUsed",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "facilitatorNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fulfillOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "matchAdvancedOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "matchOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "orderUsed", data: BytesLike): Result;

  events: {};
}

export interface Consideration extends BaseContract {
  contractName: "Consideration";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ConsiderationInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<[string]>;

    cancel(
      orders: OrderStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    facilitatorNonces(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    fulfillOrder(
      order: OrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hash(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    matchAdvancedOrders(
      orders: AdvancedOrderStruct[],
      fulfillments: AdvancedFulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    matchOrders(
      orders: OrderStruct[],
      fulfillments: FulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    orderUsed(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

  cancel(
    orders: OrderStruct[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  facilitatorNonces(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  fulfillOrder(
    order: OrderStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hash(
    orderParameters: OrderParametersStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  matchAdvancedOrders(
    orders: AdvancedOrderStruct[],
    fulfillments: AdvancedFulfillmentStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  matchOrders(
    orders: OrderStruct[],
    fulfillments: FulfillmentStruct[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  orderUsed(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<string>;

    cancel(orders: OrderStruct[], overrides?: CallOverrides): Promise<boolean>;

    facilitatorNonces(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fulfillOrder(
      order: OrderStruct,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hash(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    matchAdvancedOrders(
      orders: AdvancedOrderStruct[],
      fulfillments: AdvancedFulfillmentStruct[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    matchOrders(
      orders: OrderStruct[],
      fulfillments: FulfillmentStruct[],
      overrides?: CallOverrides
    ): Promise<ExecutionStructOutput[]>;

    name(overrides?: CallOverrides): Promise<string>;

    orderUsed(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<BigNumber>;

    cancel(
      orders: OrderStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    facilitatorNonces(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    fulfillOrder(
      order: OrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hash(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    matchAdvancedOrders(
      orders: AdvancedOrderStruct[],
      fulfillments: AdvancedFulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    matchOrders(
      orders: OrderStruct[],
      fulfillments: FulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    orderUsed(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DOMAIN_SEPARATOR(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cancel(
      orders: OrderStruct[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    facilitatorNonces(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    fulfillOrder(
      order: OrderStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hash(
      orderParameters: OrderParametersStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    matchAdvancedOrders(
      orders: AdvancedOrderStruct[],
      fulfillments: AdvancedFulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    matchOrders(
      orders: OrderStruct[],
      fulfillments: FulfillmentStruct[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    orderUsed(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
