name: Publish Docs to Central Repository
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy developer docs to repository
        if: github.ref == 'refs/heads/main'
        uses: nkoppel/push-files-to-another-repository@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: "docs/"
          destination-username: "ProjectOpenSea"
          destination-repository: "developer-docs"
          destination-directory: "seaport"
          destination-branch: "main"
          commit-username: "ProjectOpenSea-seaport"
          commit-message: "Latest docs from seaport"